
name: flutter_login
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: 5.0.1
  user_repository:
    path: user_repository
  equatable: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  bloc_test: 6.0.1
  mockito: ^4.0.0

flutter:
  uses-material-design: true